udate README.md: add the instructions to run frontend in dev mode
osscameroon/camerdevs pull request #40
Opened 2022-01-24 23:18 UTC by Zaker237

This pull request adds instructions to readme that guides a dev who want to start the frontend in dev mode.

2022-01-25 18:48 UTC, Asam237 requested changes
Add this,
To run the application in dev mode, do:
yarn dev or npm run dev

2022-01-25 20:19 UTC, Zaker237 commented
@Asam237  i added the yarn instructions as you requested

2022-01-27 05:11 UTC, Asam237 commented
In fact, it's a Nuxt JS project. First we had to use "nuxt build" to start Nuxt in development mode. However, to overcome this, we can directly use "npm run dev" or "yarn dev" 

Here is this error we get when we use "yarn start" or "npm run start" 
![nuxtstart](https://user-images.githubusercontent.com/34966088/151295769-6dffd33b-045e-451f-b41a-ace70d86d0a8.png)

2022-02-06 20:11 UTC, Asam237 approved these changes

2022-02-06 20:12 UTC, elhmn requested changes

2022-02-06 20:12 UTC, elhmn commented on README.md
> +`yarn dev`
we could have kept the `npm install` step as well. 
Also it is recommended to use npm as we don't have a `yarn.lock` file in the folder

2022-02-06 20:34 UTC, elhmn approved these changes

2022-02-06 20:46 UTC, merged